[package]
name = "vellum-sql-engine"
version = "0.1.0"
edition = "2021"


[lib]
name = "vellum_sql_engine"
path = "mod.rs"



[dependencies]
pg_query = "6.1"
vellum-contracts = { path = "../contracts" }
